//This is a theme file, please update any theme related constants here

const COLOR_PRIMARY = '#AAAFFF';
const COLOR_PRIMARY_DARK = '#FF6E6A';
const COLOR_SECONDARY = '#FFC853';

const COLOR_DARK = '#000000';
const COLOR_DEFAULT = '#333333';
const COLOR_BRIGHT = '#FFFFFF';
const COLOR_TRANSPARENT = 'transparent';

export const commonTheme = {
  COLOR_PRIMARY_DARK: COLOR_PRIMARY_DARK,
  COLOR_PRIMARY: COLOR_PRIMARY,
  COLOR_SECONDARY: COLOR_SECONDARY,
  COLOR_DEFAULT: COLOR_DEFAULT,
  COLOR_DARK: COLOR_DARK,
  COLOR_BRIGHT: COLOR_BRIGHT,
  COLOR_TRANSPARENT: COLOR_TRANSPARENT,
};
